// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Capabilities reports what search modes are available.
 */
export interface Capabilities {
    "fts": boolean;
    "vectorExtension": boolean;
    "embeddingConfigured": boolean;
    "vectorSearch": boolean;
    "reason"?: string;
}

/**
 * Hit is a unified search result.
 */
export interface Hit {
    "articleId": string;
    "title": string;
    "score": number;

    /**
     * fts|vector|hybrid
     */
    "source": string;
    "snippet"?: string;
    "distance"?: number;
}

/**
 * Result is the search response.
 */
export interface Result {
    "hits": Hit[] | null;
    "modeUsed": string;
    "warnings"?: string[] | null;
}
