// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status is the Wails-facing launch-at-login snapshot.
 */
export interface Status {
    "enabled": boolean;
    "supported": boolean;
    "error"?: string;
}
