// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status is the runtime view of the web server for the desktop UI.
 */
export interface Status {
    "running": boolean;
    "url": string;
    "lanUrl"?: string;
    "bind": string;
    "port": number;
    "error"?: string;
    "hasToken": boolean;
}
