// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Vector capability state for the opened DB.
 */
export interface VectorStatus {
    "loaded": boolean;
    "version"?: string;
    "backend"?: string;
    "path"?: string;
    "error"?: string;
}
