// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JobActivity is a live snapshot of background refresh + briefing work.
 */
export interface JobActivity {
    "refreshing": boolean;
    "feedId"?: string;
    "feedTitle"?: string;
    "pending": number;
    "queuedTitles"?: string[] | null;

    /**
     * queued | generating
     */
    "briefingState"?: string;
    "briefingPending"?: number;
    "briefingArticles"?: number;

    /**
     * ArticlesAdded is a process-lifetime insert counter (not a per-tick delta).
     */
    "articlesAdded": number;
}
