// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EmbeddingConfig is stored under settings keys embedding.*.
 */
export interface EmbeddingConfig {
    "provider": string;
    "baseUrl": string;
    "apiKey": string;
    "model": string;
    "dimensions": number;
    "batchSize": number;
}

/**
 * SearchConfig controls search mode defaults.
 */
export interface SearchConfig {
    "mode": string;
    "vectorTopK": number;
    "ftsLimit": number;
}
