// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EmbeddingConfig is stored under settings keys embedding.*.
 */
export interface EmbeddingConfig {
    "provider": string;
    "baseUrl": string;
    "apiKey": string;
    "model": string;
    "dimensions": number;
    "batchSize": number;
}

/**
 * LLMConfig is stored under settings keys llm.*.
 * OpenAI-compatible Chat Completions API (OpenAI, DeepSeek, Ollama, etc.).
 */
export interface LLMConfig {
    "provider": string;
    "baseUrl": string;
    "apiKey": string;
    "model": string;

    /**
     * 0–2, default 0.3
     */
    "temperature": number;

    /**
     * completion budget; 0 = provider default
     */
    "maxTokens": number;

    /**
     * SystemPrompt is an optional default system message for future features.
     */
    "systemPrompt": string;
}

/**
 * LibraryConfig controls background refresh behaviour.
 */
export interface LibraryConfig {
    "autoRefresh": boolean;
    "refreshIntervalMinutes": number;
}

/**
 * ReaderToolbarButtons controls which icons appear in the article reader header.
 * See DefaultReaderToolbarButtons. JSON keys match frontend settings.readerToolbar.
 */
export interface ReaderToolbarButtons {
    "zen": boolean;
    "star": boolean;
    "read": boolean;
    "summarize": boolean;
    "translate": boolean;
    "ai": boolean;
    "fetchFull": boolean;
    "markdown": boolean;
    "openOriginal": boolean;
}

/**
 * SearchConfig controls search mode defaults.
 */
export interface SearchConfig {
    "mode": string;
    "vectorTopK": number;
    "ftsLimit": number;
}

/**
 * UIPrefs holds frontend UI / reading / retention preferences.
 * JSON keys match the frontend AppSettings fields (camelCase).
 */
export interface UIPrefs {
    "markAsReadOnOpen": boolean;
    "markAsReadOnScrollEnd": boolean;

    /**
     * unread|today|starred|all
     */
    "openOnStartup": string;
    "hideReadOnStartup": boolean;

    /**
     * system|light|dark
     */
    "theme": string;

    /**
     * blue|purple|teal|orange
     */
    "accent": string;
    "compactSidebar": boolean;

    /**
     * sm|md|lg
     */
    "fontSize": string;
    "showUnreadOnly": boolean;
    "openLinksInBrowser": boolean;

    /**
     * narrow|medium|wide|fill
     */
    "readerWidth": string;

    /**
     * empty = none
     */
    "defaultFolderId": string;
    "fetchFullContent": boolean;

    /**
     * 7–365, default 90
     */
    "keepArticlesDays": number;
    "hideDuplicateTitles": boolean;
    "blockKeywords": string;
    "enableKeyboardShortcuts": boolean;
    "notifyOnNewArticles": boolean;
    "notifySound": boolean;
    "hardwareAcceleration": boolean;
    "clearCacheOnQuit": boolean;
    "developerMode": boolean;

    /**
     * NsfwMode: true = show NSFW feeds (default); false = office mode hide isNsfw feeds.
     */
    "nsfwMode": boolean;

    /**
     * AutoSummarize: when true, opening an article requests an LLM summary (if LLM configured).
     */
    "autoSummarize": boolean;

    /**
     * SelectTranslate: when true, selecting text in the reader shows AI 划词翻译.
     */
    "selectTranslate": boolean;

    /**
     * AutoFetchFull: when true, opening an article asks the LLM if the body is
     * partial; if so, automatically fetch the original page full text.
     */
    "autoFetchFull": boolean;

    /**
     * TranslateReplaceOriginal: when true, full-article translate overwrites content_html/text.
     * When false, only the bilingual overlay is shown (no body replace).
     */
    "translateReplaceOriginal": boolean;

    /**
     * ReaderToolbar: which header icons are visible in the article reader.
     */
    "readerToolbar": ReaderToolbarButtons;
}
