// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Article is a single feed item.
 */
export interface Article {
    "id": string;
    "feedId": string;
    "guid"?: string | null;
    "url": string;
    "title": string;
    "author"?: string | null;
    "summary"?: string | null;
    "contentHtml"?: string | null;
    "contentText"?: string | null;

    /**
     * TranslationRaw is bilingual marker text (<<o>>/<<t>>) kept next to the original body.
     * Original content_html is never replaced by translate.
     */
    "translationRaw"?: string | null;
    "translationLang"?: string | null;
    "imageUrl"?: string | null;
    "publishedAt"?: string | null;
    "fetchedAt": string;
    "isRead": boolean;
    "isStarred": boolean;

    /**
     * FullContentFetched is true after a successful full-page fetch replaced the body.
     * Used to skip auto “partial body” detection on subsequent opens.
     */
    "fullContentFetched": boolean;
}

/**
 * Feed is an RSS/Atom subscription.
 */
export interface Feed {
    "id": string;
    "folderId"?: string | null;
    "title": string;
    "siteUrl"?: string | null;
    "feedUrl": string;
    "faviconUrl"?: string | null;
    "etag"?: string | null;
    "lastModified"?: string | null;
    "lastFetchedAt"?: string | null;
    "lastError"?: string | null;
    "isPaused": boolean;

    /**
     * RefreshIntervalMinutes is per-feed auto-refresh interval.
     * 0 means use the global LibraryConfig default.
     */
    "refreshIntervalMinutes": number;

    /**
     * KeepArticlesDays is per-feed retention for non-starred articles.
     * 0 means use the global UIPrefs keepArticlesDays; otherwise [7, 365].
     */
    "keepArticlesDays": number;

    /**
     * TitleUserSet is true when the user renamed the feed; refresh must not overwrite title.
     */
    "titleUserSet": boolean;

    /**
     * IsNsfw marks a sensitive feed. When UIPrefs.nsfwMode is false, UI hides this feed.
     */
    "isNsfw": boolean;
    "unreadCount": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * Folder groups feeds in the sidebar.
 */
export interface Folder {
    "id": string;
    "name": string;
    "parentId"?: string | null;
    "sortOrder": number;

    /**
     * IsNsfw marks a sensitive folder. When UIPrefs.nsfwMode is false, UI hides
     * this folder and its feeds; article lists/search also exclude them.
     */
    "isNsfw": boolean;
    "createdAt": string;
    "updatedAt": string;
}
