// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Article is a single feed item.
 */
export interface Article {
    "id": string;
    "feedId": string;
    "guid"?: string | null;
    "url": string;
    "title": string;
    "author"?: string | null;
    "summary"?: string | null;
    "contentHtml"?: string | null;
    "contentText"?: string | null;
    "imageUrl"?: string | null;
    "publishedAt"?: string | null;
    "fetchedAt": string;
    "isRead": boolean;
    "isStarred": boolean;
}

/**
 * Feed is an RSS/Atom subscription.
 */
export interface Feed {
    "id": string;
    "folderId"?: string | null;
    "title": string;
    "siteUrl"?: string | null;
    "feedUrl": string;
    "faviconUrl"?: string | null;
    "etag"?: string | null;
    "lastModified"?: string | null;
    "lastFetchedAt"?: string | null;
    "lastError"?: string | null;
    "isPaused": boolean;

    /**
     * RefreshIntervalMinutes is per-feed auto-refresh interval.
     * 0 means use the global LibraryConfig default.
     */
    "refreshIntervalMinutes": number;

    /**
     * TitleUserSet is true when the user renamed the feed; refresh must not overwrite title.
     */
    "titleUserSet": boolean;
    "unreadCount": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * Folder groups feeds in the sidebar.
 */
export interface Folder {
    "id": string;
    "name": string;
    "parentId"?: string | null;
    "sortOrder": number;
    "createdAt": string;
    "updatedAt": string;
}
