// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as appsvc$0 from "../../../../../lrss/internal/appsvc/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "llm:stream": appsvc$0.LLMStreamEvent;
            "time": string;
        }
    }
}
