// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CheckResult is returned to the UI.
 */
export interface CheckResult {
    /**
     * upToDate | updateAvailable | error
     */
    "status": string;
    "current": string;
    "latest"?: string;
    "htmlUrl"?: string;
    "name"?: string;
    "message"?: string;
    "asset"?: string;
    "canInstall": boolean;
}

/**
 * InstallResult is returned after scheduling replacement.
 */
export interface InstallResult {
    "ok": boolean;
    "message": string;
    "latest"?: string;
    "asset"?: string;
}
