// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SmartCounts is the sidebar badge totals (independent of the current list page).
 */
export interface SmartCounts {
    "unread": number;
    "today": number;
    "starred": number;
    "all": number;
    "recent": number;

    /**
     * Kept is the unread count of articles in article_keeps (sidebar badge).
     */
    "kept": number;
}
