// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService exposes user-triggered LLM features to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplySuggestedFolder moves the article's feed into folderId (existing MoveFeed).
 */
export function ApplySuggestedFolder(articleId: string, folderId: string): $CancellablePromise<void> {
    return $Call.ByID(120519033, articleId, folderId);
}

/**
 * Ask answers a question about the article (empty question → default overview in UI locale).
 */
export function Ask(articleId: string, question: string, locale: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(3630355463, articleId, question, locale);
}

/**
 * ClassifyPromo classifies the article as organic / promo / unclear (user-triggered).
 * locale is the app UI language for explanation text.
 */
export function ClassifyPromo(articleId: string, locale: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(3093298899, articleId, locale);
}

/**
 * ClearTranslation removes saved bilingual text; original body is unchanged.
 */
export function ClearTranslation(articleId: string): $CancellablePromise<void> {
    return $Call.ByID(2982864194, articleId);
}

/**
 * DailyDigest builds a Markdown digest of today's unread articles (Top N, default 12).
 * locale controls output language (app UI language).
 */
export function DailyDigest(limit: number, locale: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(299240351, limit, locale);
}

/**
 * DetectContentFullness judges whether the stored body looks complete or partial.
 * Verdict: full|partial|unclear|skipped_no_url|already_fetched. Does not fetch the page.
 */
export function DetectContentFullness(articleId: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(1923791988, articleId);
}

/**
 * EnsureFullContent uses the LLM to judge whether the stored body is only a
 * partial excerpt; if partial (or empty), fetches the original page via fulltext.
 * Verdict: full|partial|fetched|skipped_no_url|skipped_unclear
 * Prefer frontend DetectContentFullness + FetchFullContent when UI needs a
 * “starting fetch” toast before body replacement.
 */
export function EnsureFullContent(articleId: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(643518686, articleId);
}

/**
 * IsLLMConfigured reports whether chat LLM is ready (for UI enablement).
 */
export function IsLLMConfigured(): $CancellablePromise<boolean> {
    return $Call.ByID(2847594217);
}

/**
 * SuggestFolders returns tag/folder suggestions for an article.
 * When LLM is off, returns local-rule tags only. locale is app UI language.
 */
export function SuggestFolders(articleId: string, locale: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(1013387109, articleId, locale);
}

/**
 * Summarize streams a deck-style summary into the reader (via llm:stream events),
 * then replaces the article's stored summary. locale is the app UI language.
 */
export function Summarize(articleId: string, locale: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(2212174867, articleId, locale);
}

/**
 * Translate streams a bilingual interlinear translation (llm:stream, feature=translate).
 * targetLang is e.g. zh-CN or en. Output uses <<o>>/<<t>> pairs.
 * Always keeps the original content_html; bilingual text is saved on the article as translationRaw.
 */
export function Translate(articleId: string, targetLang: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(1790707048, articleId, targetLang);
}

/**
 * TranslateSelection translates a short in-reader text selection (划词翻译).
 * Uses a fixed plain-translation prompt (not bilingual markers). targetLang e.g. zh-CN / en.
 */
export function TranslateSelection(text: string, targetLang: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(3853920870, text, targetLang);
}
