// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService exposes user-triggered LLM features to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplySuggestedFolder moves the article's feed into folderId (existing MoveFeed).
 */
export function ApplySuggestedFolder(articleId: string, folderId: string): $CancellablePromise<void> {
    return $Call.ByID(120519033, articleId, folderId);
}

/**
 * Ask answers a question about the article (empty question → default overview in UI locale).
 */
export function Ask(articleId: string, question: string, locale: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(3630355463, articleId, question, locale);
}

/**
 * ClassifyPromo classifies the article as organic / promo / unclear (user-triggered).
 * locale is the app UI language for explanation text.
 */
export function ClassifyPromo(articleId: string, locale: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(3093298899, articleId, locale);
}

/**
 * DailyDigest builds a Markdown digest of today's unread articles (Top N, default 12).
 * locale controls output language (app UI language).
 */
export function DailyDigest(limit: number, locale: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(299240351, limit, locale);
}

/**
 * IsLLMConfigured reports whether chat LLM is ready (for UI enablement).
 */
export function IsLLMConfigured(): $CancellablePromise<boolean> {
    return $Call.ByID(2847594217);
}

/**
 * SuggestFolders returns tag/folder suggestions for an article.
 * When LLM is off, returns local-rule tags only. locale is app UI language.
 */
export function SuggestFolders(articleId: string, locale: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(1013387109, articleId, locale);
}

/**
 * Summarize streams a deck-style summary into the reader (via llm:stream events),
 * then replaces the article's stored summary. locale is the app UI language.
 */
export function Summarize(articleId: string, locale: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(2212174867, articleId, locale);
}

/**
 * Translate translates an article into targetLang (e.g. zh-CN, en).
 */
export function Translate(articleId: string, targetLang: string): $CancellablePromise<$models.AIResult> {
    return $Call.ByID(1790707048, articleId, targetLang);
}
