// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArticleService is the Wails-facing article API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repo$0 from "../repo/models.js";

/**
 * CreateKeepFolder creates a 精选 child folder. Empty parentId = first level.
 */
export function CreateKeepFolder(name: string, parentId: string): $CancellablePromise<model$0.KeepFolder> {
    return $Call.ByID(422116441, name, parentId);
}

/**
 * DeleteKeepFolder removes a 精选 folder; articles return to the root.
 */
export function DeleteKeepFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(682911526, id);
}

/**
 * FetchFullContent downloads the original article page (fingerprint HTTP / surf),
 * extracts full HTML body, saves it, and returns the updated article.
 * Use when the feed only ships a partial summary in XML.
 * Bounded so a hung remote page cannot block other ArticleService calls forever.
 */
export function FetchFullContent(id: string): $CancellablePromise<model$0.Article> {
    return $Call.ByID(2551682350, id);
}

/**
 * Get returns one article with sanitized HTML.
 */
export function Get(id: string): $CancellablePromise<model$0.Article> {
    return $Call.ByID(3710228952, id);
}

/**
 * Keep files an article into the 精选 collection (manual).
 */
export function Keep(id: string): $CancellablePromise<void> {
    return $Call.ByID(365744413, id);
}

/**
 * List returns articles for a collection (unread|today|starred|all|recent|kept|feed:ID|folder:ID).
 * Office-mode NSFW filtering applies only to smart lists. Explicit feed:/folder:
 * collections always return their articles so a just-subscribed sensitive feed is
 * still readable after add (sidebar may still hide it).
 */
export function List(collection: string, limit: number, offset: number): $CancellablePromise<model$0.Article[] | null> {
    return $Call.ByID(3903554996, collection, limit, offset);
}

/**
 * ListKeepFolders returns user folders under the virtual 精选 root.
 */
export function ListKeepFolders(): $CancellablePromise<model$0.KeepFolder[] | null> {
    return $Call.ByID(3352086970);
}

/**
 * MarkAllRead marks a collection as read.
 */
export function MarkAllRead(collection: string): $CancellablePromise<void> {
    return $Call.ByID(3784220600, collection);
}

/**
 * RecordOpened records that the reader opened an article (recent-read list).
 * keep comes from UIPrefs.RecentReadLimit (default 50 if store is missing or load fails).
 */
export function RecordOpened(id: string): $CancellablePromise<void> {
    return $Call.ByID(398197724, id);
}

/**
 * RenameKeepFolder renames a 精选 folder.
 */
export function RenameKeepFolder(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3445320663, id, name);
}

/**
 * SetKeepFolder moves a kept article to a 精选 folder. Empty folderId = root.
 */
export function SetKeepFolder(articleId: string, folderId: string): $CancellablePromise<void> {
    return $Call.ByID(3324360765, articleId, folderId);
}

/**
 * SetRead marks read state.
 */
export function SetRead(id: string, read: boolean): $CancellablePromise<void> {
    return $Call.ByID(2247240152, id, read);
}

/**
 * SetStarred marks starred state.
 */
export function SetStarred(id: string, starred: boolean): $CancellablePromise<void> {
    return $Call.ByID(3275888491, id, starred);
}

/**
 * SmartCounts returns full library totals for sidebar badges (not capped by list limit).
 */
export function SmartCounts(): $CancellablePromise<repo$0.SmartCounts> {
    return $Call.ByID(1651368005);
}

/**
 * Unkeep removes an article from the 精选 collection.
 */
export function Unkeep(id: string): $CancellablePromise<void> {
    return $Call.ByID(1966284558, id);
}
