// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BriefingService is the Wails-facing AI briefing API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(454669727, id);
}

export function Get(id: string): $CancellablePromise<model$0.Briefing> {
    return $Call.ByID(3277408784, id);
}

export function List(): $CancellablePromise<model$0.Briefing[] | null> {
    return $Call.ByID(2227788284);
}

/**
 * Retry re-generates a failed briefing from its stored source articles.
 */
export function Retry(id: string): $CancellablePromise<model$0.Briefing> {
    return $Call.ByID(747276062, id);
}

export function SetRead(id: string, read: boolean): $CancellablePromise<void> {
    return $Call.ByID(3304552528, id, read);
}

export function SetStarred(id: string, starred: boolean): $CancellablePromise<void> {
    return $Call.ByID(4105688403, id, starred);
}

export function UnreadCount(): $CancellablePromise<number> {
    return $Call.ByID(4021232762);
}
