// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FeedService is the Wails-facing feed API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFeed subscribes to a feed URL. Empty folderId means no folder.
 */
export function AddFeed(feedURL: string, folderId: string): $CancellablePromise<model$0.Feed> {
    return $Call.ByID(4023383239, feedURL, folderId);
}

/**
 * DeleteFeed removes a subscription.
 */
export function DeleteFeed(id: string): $CancellablePromise<void> {
    return $Call.ByID(1993950911, id);
}

/**
 * ListFeeds returns all feeds with unread counts.
 */
export function ListFeeds(): $CancellablePromise<model$0.Feed[] | null> {
    return $Call.ByID(671146573);
}

/**
 * ListFolders returns all folders.
 */
export function ListFolders(): $CancellablePromise<model$0.Folder[] | null> {
    return $Call.ByID(2956343813);
}

/**
 * RefreshAll refreshes all non-paused feeds.
 */
export function RefreshAll(): $CancellablePromise<$models.RefreshAllResult> {
    return $Call.ByID(398512294);
}

/**
 * RefreshFeed re-fetches one feed.
 */
export function RefreshFeed(id: string): $CancellablePromise<$models.RefreshResult> {
    return $Call.ByID(4066473343, id);
}
