// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FeedService is the Wails-facing feed API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../service/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFeed subscribes to a feed URL. Empty folderId means no folder.
 */
export function AddFeed(feedURL: string, folderId: string): $CancellablePromise<model$0.Feed> {
    return $Call.ByID(4023383239, feedURL, folderId);
}

/**
 * ClearAllSubscriptions removes every feed, article, and folder. Irreversible.
 */
export function ClearAllSubscriptions(): $CancellablePromise<$models.ClearAllResult> {
    return $Call.ByID(4271003402);
}

/**
 * CreateFolder creates a folder. Empty parentId means root.
 */
export function CreateFolder(name: string, parentId: string): $CancellablePromise<model$0.Folder> {
    return $Call.ByID(3823558712, name, parentId);
}

/**
 * DeleteFeed removes a subscription.
 */
export function DeleteFeed(id: string): $CancellablePromise<void> {
    return $Call.ByID(1993950911, id);
}

/**
 * DeleteFolder removes a folder (feeds become unfiled).
 */
export function DeleteFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(1978788375, id);
}

/**
 * ExportOPML returns the subscription tree as OPML 2.0 XML text.
 */
export function ExportOPML(): $CancellablePromise<string> {
    return $Call.ByID(3473081360);
}

/**
 * ImportOPML imports an OPML document.
 * Prefer fetch=false from the UI so the call returns after writing subscriptions;
 * then refresh AddedFeedIDs with RefreshFeed for progress. fetch=true blocks until
 * every new feed is fetched (slow for large OPML files).
 * Existing feed URLs are merged (folder / unlocked title / empty site URL), not ignored.
 */
export function ImportOPML(xml: string, fetch: boolean): $CancellablePromise<$models.OPMLImportResult> {
    return $Call.ByID(3830505915, xml, fetch);
}

/**
 * JobActivity is a live snapshot of feed refresh + briefing work.
 */
export function JobActivity(): $CancellablePromise<service$0.JobActivity> {
    return $Call.ByID(592667890);
}

/**
 * ListFeeds returns all feeds with unread counts.
 */
export function ListFeeds(): $CancellablePromise<model$0.Feed[] | null> {
    return $Call.ByID(671146573);
}

/**
 * ListFolders returns all folders.
 */
export function ListFolders(): $CancellablePromise<model$0.Folder[] | null> {
    return $Call.ByID(2956343813);
}

/**
 * MoveFeed assigns a feed to a folder. Empty folderId means unfiled.
 */
export function MoveFeed(feedId: string, folderId: string): $CancellablePromise<void> {
    return $Call.ByID(1053389845, feedId, folderId);
}

/**
 * RefreshAll queues every active feed and refreshes one paced batch (same cap
 * as auto-refresh). Remaining feeds drain in the background loop.
 */
export function RefreshAll(): $CancellablePromise<$models.RefreshAllResult> {
    return $Call.ByID(398512294);
}

/**
 * RefreshFeed re-fetches one feed.
 * Bounded so a hung remote feed cannot leave the UI spinner spinning forever.
 */
export function RefreshFeed(id: string): $CancellablePromise<$models.RefreshResult> {
    return $Call.ByID(4066473343, id);
}

/**
 * RenameFeed sets a custom display title (will not be overwritten by refresh).
 */
export function RenameFeed(id: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(1087303506, id, title);
}

/**
 * RenameFolder renames a folder.
 */
export function RenameFolder(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2070165874, id, name);
}

/**
 * SetFeedKeepArticlesDays sets per-feed article retention days.
 * 0 = use global UIPrefs keepArticlesDays; otherwise clamped to [7, 365].
 */
export function SetFeedKeepArticlesDays(id: string, days: number): $CancellablePromise<void> {
    return $Call.ByID(892312109, id, days);
}

/**
 * SetFeedNsfw marks or unmarks a feed as sensitive (NSFW).
 */
export function SetFeedNsfw(id: string, nsfw: boolean): $CancellablePromise<void> {
    return $Call.ByID(2554505244, id, nsfw);
}

/**
 * SetFeedPaused pauses or unpauses a feed.
 */
export function SetFeedPaused(id: string, paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(3296238782, id, paused);
}

/**
 * SetFeedRefreshInterval sets per-feed auto-refresh minutes.
 * 0 means follow the global default; otherwise clamped to [5, 180].
 */
export function SetFeedRefreshInterval(id: string, minutes: number): $CancellablePromise<void> {
    return $Call.ByID(1949052462, id, minutes);
}

/**
 * SetFeedURL updates the subscription feed URL (http/https). Keeps articles;
 * rejects URLs already used by another feed.
 */
export function SetFeedURL(id: string, feedURL: string): $CancellablePromise<void> {
    return $Call.ByID(3854602269, id, feedURL);
}

/**
 * SetFolderDisplayMode sets the article list layout for a folder: "list" or "cards".
 */
export function SetFolderDisplayMode(id: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(3043437529, id, mode);
}

/**
 * SetFolderNsfw marks or unmarks a folder as sensitive (NSFW).
 * In office mode the folder and its feeds are hidden from the sidebar and lists.
 */
export function SetFolderNsfw(id: string, nsfw: boolean): $CancellablePromise<void> {
    return $Call.ByID(2232540948, id, nsfw);
}
