// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RefreshAllResult is returned by RefreshAll.
 */
export interface RefreshAllResult {
    "feedsOk": number;
    "feedsErr": number;
    "articlesAdded": number;
}

/**
 * RefreshResult is returned by RefreshFeed.
 */
export interface RefreshResult {
    "added": number;
}
