// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIResult is the JSON shape returned to the UI.
 */
export interface AIResult {
    "markdown": string;
    "feature": string;
    "model": string;
    "cached": boolean;
    "folderId"?: string;
    "folderName"?: string;
    "verdict"?: string;
}

/**
 * ClearAllResult is returned by ClearAllSubscriptions.
 */
export interface ClearAllResult {
    "feedsDeleted": number;
    "foldersDeleted": number;
}

/**
 * OPMLImportResult is the Wails-facing import summary (mirrors service.OPMLImportResult).
 */
export interface OPMLImportResult {
    "foldersCreated": number;
    "feedsAdded": number;
    "feedsSkipped": number;
    "feedsFailed": number;
    "errors": string[] | null;
    "addedFeedIds": string[] | null;
}

/**
 * PurgeResult is returned by PurgeOldArticles for the frontend.
 */
export interface PurgeResult {
    "deleted": number;
}

/**
 * RefreshAllResult is returned by RefreshAll.
 */
export interface RefreshAllResult {
    "feedsOk": number;
    "feedsErr": number;
    "articlesAdded": number;
}

/**
 * RefreshResult is returned by RefreshFeed.
 */
export interface RefreshResult {
    "added": number;
}
