// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as web$0 from "../web/models.js";

/**
 * AIResult is the JSON shape returned to the UI.
 */
export interface AIResult {
    "markdown": string;
    "feature": string;
    "model": string;
    "cached": boolean;
    "folderId"?: string;
    "folderName"?: string;
    "verdict"?: string;

    /**
     * KeptOriginal is always true for translate: original body is never overwritten.
     */
    "keptOriginal"?: boolean;
    "translationRaw"?: string;
    "translationLang"?: string;
}

/**
 * CacheClearResult is returned by ClearLLMCache.
 */
export interface CacheClearResult {
    "deleted": number;
}

/**
 * ChatHistoryResult is the persisted transcript for an article.
 */
export interface ChatHistoryResult {
    "sessionId": string;
    "articleId": string;
    "messages": model$0.ChatMessage[] | null;
}

/**
 * ChatSendRequest is one user turn against the current article and/or library.
 */
export interface ChatSendRequest {
    "sessionId": string;
    "message": string;
    "articleId": string;
    "attachIds": string[] | null;
    "collectionId": string;
    "selection": string;
    "locale": string;
    "useLibrary": boolean;
}

/**
 * ChatSendResult is the completed assistant turn.
 */
export interface ChatSendResult {
    "sessionId": string;
    "messageId": string;
    "markdown": string;
    "model": string;
    "citations"?: model$0.ChatCitation[] | null;
}

/**
 * ClearAllResult is returned by ClearAllSubscriptions.
 */
export interface ClearAllResult {
    "feedsDeleted": number;
    "foldersDeleted": number;
}

/**
 * LLMStreamEvent is emitted to the frontend during streaming AI features.
 */
export interface LLMStreamEvent {
    "articleId": string;
    "sessionId"?: string;
    "feature": string;
    "delta": string;
    "text": string;
    "done": boolean;
    "error"?: string;
    "model"?: string;
    "cached"?: boolean;
}

/**
 * OPMLImportResult is the Wails-facing import summary (mirrors service.OPMLImportResult).
 */
export interface OPMLImportResult {
    "foldersCreated": number;
    "feedsAdded": number;
    "feedsUpdated": number;
    "feedsSkipped": number;
    "feedsFailed": number;
    "errors": string[] | null;
    "addedFeedIds": string[] | null;
}

/**
 * PurgeResult is returned by PurgeOldArticles for the frontend.
 */
export interface PurgeResult {
    "deleted": number;
}

/**
 * RefreshAllResult is returned by RefreshAll (one paced batch; rest may be pending).
 */
export interface RefreshAllResult {
    "feedsOk": number;
    "feedsErr": number;
    "articlesAdded": number;

    /**
     * FeedsPending is force-queue remaining after this call (background continues).
     */
    "feedsPending": number;
}

/**
 * RefreshResult is returned by RefreshFeed.
 */
export interface RefreshResult {
    "added": number;
}

/**
 * ScanKeepResult is returned by ScanUnreadForKeep.
 */
export interface ScanKeepResult {
    "queued": number;
}

/**
 * SyncPullResult is returned after downloading and importing OPML.
 */
export interface SyncPullResult {
    "bytes": number;
    "imported": number;
    "skipped": number;
    "folders": number;
    "pulledAt": string;
    "fetchAfter": boolean;
}

/**
 * SyncPushResult is returned after uploading OPML.
 */
export interface SyncPushResult {
    "bytes": number;
    "pushedAt": string;
}

/**
 * SyncTestResult is returned by TestSyncConnection.
 */
export interface SyncTestResult {
    "ok": boolean;
    "message": string;
}

/**
 * WebAccessStatus is the desktop UI view of the browser HTTP server.
 * Mirrors web.Status with json tags for Wails.
 */
export type WebAccessStatus = web$0.Status;
