// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is exposed to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as autostart$0 from "../autostart/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as search$0 from "../search/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearLLMCache wipes AI feature result cache (summarize/translate/etc.).
 */
export function ClearLLMCache(): $CancellablePromise<$models.CacheClearResult> {
    return $Call.ByID(3052885573);
}

/**
 * EnsureNotificationPermission requests OS notification permission when needed.
 */
export function EnsureNotificationPermission(): $CancellablePromise<boolean> {
    return $Call.ByID(2837513543);
}

/**
 * GetEmbeddingConfig returns masked embedding settings.
 */
export function GetEmbeddingConfig(): $CancellablePromise<settings$0.EmbeddingConfig> {
    return $Call.ByID(1948392802);
}

/**
 * GetLLMConfig returns masked chat LLM settings.
 */
export function GetLLMConfig(): $CancellablePromise<settings$0.LLMConfig> {
    return $Call.ByID(3544433808);
}

/**
 * GetLaunchAtLogin reports whether the OS will start LRSS at login.
 */
export function GetLaunchAtLogin(): $CancellablePromise<autostart$0.Status> {
    return $Call.ByID(3479812466);
}

/**
 * GetLibraryConfig returns auto-refresh settings.
 */
export function GetLibraryConfig(): $CancellablePromise<settings$0.LibraryConfig> {
    return $Call.ByID(422396684);
}

/**
 * GetSearchCapabilities reports FTS/vector availability.
 */
export function GetSearchCapabilities(): $CancellablePromise<search$0.Capabilities> {
    return $Call.ByID(2922587253);
}

/**
 * GetSearchConfig returns search mode settings.
 */
export function GetSearchConfig(): $CancellablePromise<settings$0.SearchConfig> {
    return $Call.ByID(3270384893);
}

/**
 * GetUIPrefs returns UI / reading / retention preferences (defaults when unset).
 */
export function GetUIPrefs(): $CancellablePromise<settings$0.UIPrefs> {
    return $Call.ByID(3360190745);
}

/**
 * GetVectorStatus returns sqlite-vector load status.
 */
export function GetVectorStatus(): $CancellablePromise<db$0.VectorStatus> {
    return $Call.ByID(3325615142);
}

/**
 * GetWebAccessConfig returns persisted web access settings.
 */
export function GetWebAccessConfig(): $CancellablePromise<settings$0.WebAccessConfig> {
    return $Call.ByID(3029602495);
}

/**
 * GetWebAccessStatus returns whether the HTTP server is running and its URL.
 */
export function GetWebAccessStatus(): $CancellablePromise<$models.WebAccessStatus> {
    return $Call.ByID(1905500343);
}

/**
 * LLMCacheCount returns how many rows are in llm_feature_cache (diagnostics).
 */
export function LLMCacheCount(): $CancellablePromise<number> {
    return $Call.ByID(2097275073);
}

/**
 * ListSystemFonts returns installed / common font family names for the reading
 * typography picker (sorted, unique). Safe for CSS font-family selection.
 */
export function ListSystemFonts(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2348298818);
}

/**
 * PurgeOldArticles deletes non-starred articles older than the current keepArticlesDays.
 */
export function PurgeOldArticles(): $CancellablePromise<$models.PurgeResult> {
    return $Call.ByID(752356818);
}

/**
 * RebuildAllEmbeddings invalidates all vectors, re-queues every article, and
 * processes batches until idle (or max rounds). Requires embedding configured.
 * Returns processed article count and worker rounds.
 */
export function RebuildAllEmbeddings(): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByID(900236041);
}

/**
 * RegenerateWebAccessToken creates a new token, saves, and restarts if enabled.
 */
export function RegenerateWebAccessToken(): $CancellablePromise<settings$0.WebAccessConfig> {
    return $Call.ByID(2397339906);
}

/**
 * RunEmbedOnce processes a batch of pending embeddings (manual trigger).
 */
export function RunEmbedOnce(limit: number): $CancellablePromise<number> {
    return $Call.ByID(618325770, limit);
}

/**
 * SetEmbeddingConfig validates and saves embedding settings.
 * If model/dimensions change, embeddings are invalidated and re-queued.
 */
export function SetEmbeddingConfig(cfg: settings$0.EmbeddingConfig): $CancellablePromise<void> {
    return $Call.ByID(3872667326, cfg);
}

/**
 * SetLLMConfig validates and saves chat LLM settings.
 * When the UI sends a masked API key, the previous key is kept.
 */
export function SetLLMConfig(cfg: settings$0.LLMConfig): $CancellablePromise<void> {
    return $Call.ByID(1617502588, cfg);
}

/**
 * SetLaunchAtLogin enables or disables OS launch-at-login, then returns the current status.
 */
export function SetLaunchAtLogin(enabled: boolean): $CancellablePromise<autostart$0.Status> {
    return $Call.ByID(2024734758, enabled);
}

/**
 * SetLibraryConfig validates (clamps interval) and saves library settings.
 */
export function SetLibraryConfig(cfg: settings$0.LibraryConfig): $CancellablePromise<void> {
    return $Call.ByID(2009951272, cfg);
}

/**
 * SetSearchConfig saves search mode settings.
 */
export function SetSearchConfig(cfg: settings$0.SearchConfig): $CancellablePromise<void> {
    return $Call.ByID(2127070257, cfg);
}

/**
 * SetUIPrefs normalizes and persists UI preferences.
 * If keepArticlesDays changed, a background purge is scheduled.
 */
export function SetUIPrefs(cfg: settings$0.UIPrefs): $CancellablePromise<void> {
    return $Call.ByID(3151085653, cfg);
}

/**
 * SetWebAccessConfig saves settings and starts/stops/rebinds the HTTP server.
 */
export function SetWebAccessConfig(cfg: settings$0.WebAccessConfig): $CancellablePromise<$models.WebAccessStatus> {
    return $Call.ByID(4119432731, cfg);
}

/**
 * TestLLMConfig tries a minimal chat completion with the given config
 * (or saved config if fields are empty / key is masked). Returns a short reply snippet.
 */
export function TestLLMConfig(cfg: settings$0.LLMConfig): $CancellablePromise<string> {
    return $Call.ByID(2869665982, cfg);
}

/**
 * TestNotification sends a sample system notification (settings panel).
 */
export function TestNotification(): $CancellablePromise<void> {
    return $Call.ByID(1990489998);
}
