// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is exposed to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as search$0 from "../search/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EnsureNotificationPermission requests OS notification permission when needed.
 */
export function EnsureNotificationPermission(): $CancellablePromise<boolean> {
    return $Call.ByID(2837513543);
}

/**
 * GetEmbeddingConfig returns masked embedding settings.
 */
export function GetEmbeddingConfig(): $CancellablePromise<settings$0.EmbeddingConfig> {
    return $Call.ByID(1948392802);
}

/**
 * GetLibraryConfig returns auto-refresh settings.
 */
export function GetLibraryConfig(): $CancellablePromise<settings$0.LibraryConfig> {
    return $Call.ByID(422396684);
}

/**
 * GetSearchCapabilities reports FTS/vector availability.
 */
export function GetSearchCapabilities(): $CancellablePromise<search$0.Capabilities> {
    return $Call.ByID(2922587253);
}

/**
 * GetSearchConfig returns search mode settings.
 */
export function GetSearchConfig(): $CancellablePromise<settings$0.SearchConfig> {
    return $Call.ByID(3270384893);
}

/**
 * GetUIPrefs returns UI / reading / retention preferences (defaults when unset).
 */
export function GetUIPrefs(): $CancellablePromise<settings$0.UIPrefs> {
    return $Call.ByID(3360190745);
}

/**
 * GetVectorStatus returns sqlite-vector load status.
 */
export function GetVectorStatus(): $CancellablePromise<db$0.VectorStatus> {
    return $Call.ByID(3325615142);
}

/**
 * PurgeOldArticles deletes non-starred articles older than the current keepArticlesDays.
 */
export function PurgeOldArticles(): $CancellablePromise<$models.PurgeResult> {
    return $Call.ByID(752356818);
}

/**
 * RebuildAllEmbeddings invalidates all vectors, re-queues every article, and
 * processes batches until idle (or max rounds). Requires embedding configured.
 * Returns processed article count and worker rounds.
 */
export function RebuildAllEmbeddings(): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByID(900236041);
}

/**
 * RunEmbedOnce processes a batch of pending embeddings (manual trigger).
 */
export function RunEmbedOnce(limit: number): $CancellablePromise<number> {
    return $Call.ByID(618325770, limit);
}

/**
 * SetEmbeddingConfig validates and saves embedding settings.
 * If model/dimensions change, embeddings are invalidated and re-queued.
 */
export function SetEmbeddingConfig(cfg: settings$0.EmbeddingConfig): $CancellablePromise<void> {
    return $Call.ByID(3872667326, cfg);
}

/**
 * SetLibraryConfig validates (clamps interval) and saves library settings.
 */
export function SetLibraryConfig(cfg: settings$0.LibraryConfig): $CancellablePromise<void> {
    return $Call.ByID(2009951272, cfg);
}

/**
 * SetSearchConfig saves search mode settings.
 */
export function SetSearchConfig(cfg: settings$0.SearchConfig): $CancellablePromise<void> {
    return $Call.ByID(2127070257, cfg);
}

/**
 * SetUIPrefs normalizes and persists UI preferences.
 * If keepArticlesDays changed, a background purge is scheduled.
 */
export function SetUIPrefs(cfg: settings$0.UIPrefs): $CancellablePromise<void> {
    return $Call.ByID(3151085653, cfg);
}

/**
 * TestNotification sends a sample system notification (settings panel).
 */
export function TestNotification(): $CancellablePromise<void> {
    return $Call.ByID(1990489998);
}
