// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService exposes subscription-only remote sync (OPML via WebDAV / S3).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSyncConfig returns masked sync settings.
 */
export function GetSyncConfig(): $CancellablePromise<settings$0.SyncConfig> {
    return $Call.ByID(3592591160);
}

/**
 * PullSubscriptions downloads remote OPML and imports subscriptions.
 * fetchAfter controls whether new feeds are refreshed immediately.
 * Does not merge reading state.
 */
export function PullSubscriptions(fetchAfter: boolean): $CancellablePromise<$models.SyncPullResult> {
    return $Call.ByID(1167644950, fetchAfter);
}

/**
 * PushSubscriptions exports local feeds as OPML and uploads to the remote.
 * Does not include reading state.
 */
export function PushSubscriptions(): $CancellablePromise<$models.SyncPushResult> {
    return $Call.ByID(3820788095);
}

/**
 * SetSyncConfig saves sync settings. Masked secrets keep previous values.
 */
export function SetSyncConfig(cfg: settings$0.SyncConfig): $CancellablePromise<void> {
    return $Call.ByID(138831228, cfg);
}

/**
 * TestSyncConnection verifies the saved (or provided) remote is reachable.
 * When cfg fields are partial / secrets masked, merges with saved config.
 */
export function TestSyncConnection(cfg: settings$0.SyncConfig): $CancellablePromise<$models.SyncTestResult> {
    return $Call.ByID(3050418324, cfg);
}
