// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService checks GitHub Releases and can download+install for this platform.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";

/**
 * CheckForUpdate returns latest release status for this platform.
 */
export function CheckForUpdate(): $CancellablePromise<update$0.CheckResult> {
    return $Call.ByID(262288951);
}

/**
 * DownloadAndInstall downloads the matching release asset, schedules replace-on-exit, then quits.
 * The frontend should show a short "restarting" message; the process will exit shortly after.
 */
export function DownloadAndInstall(): $CancellablePromise<update$0.InstallResult> {
    return $Call.ByID(2595690109);
}
